FROM golang:1.13.8 as build

WORKDIR /go/src/github.com/mongodb/mongo-tools
COPY mongo-tools/ .
RUN CGO_ENABLED=0 go build -o /bin/mongorestore mongorestore/main/mongorestore.go

FROM scratch
COPY --from=build /bin/mongorestore /bin/mongorestore
ENTRYPOINT ["/bin/mongorestore"]
