apiVersion: v1
kind: Service
metadata:
  name: fastapitest
  labels:
    run: fastapitest
spec:
  selector:
    run: fastapitest
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapitest
spec:
  selector: 
    matchLabels:
      run: fastapitest
  replicas: 2
  template:
    metadata:
      labels:
        run: fastapitest
    spec:
      containers:
      - image: fastapitest
        name: fastapitest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 2222
          initialDelaySeconds: 4
          periodSeconds: 10
        env:
        - name: DB
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: user
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: host
        ports:
        - containerPort: 2222
          name: http
          protocol: TCP
