apiVersion: v1
kind: Pod
metadata:
  name: fastapitest
spec:
  containers:
  - image: fastapitest
    name: fastapitest
    imagePullPolicy: Never
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
    env:
    - name: DB
      valueFrom:
        secretKeyRef:
          name: fastapi-secret
          key: db
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: fastapi-secret
          key: user
    - name: DB_PW
      valueFrom:
        secretKeyRef:
          name: fastapi-secret
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: fastapi-secret
          key: host
    ports:
    - containerPort: 2222
      name: http
      protocol: TCP
