apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels: 
    volume: mongo-vol
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  local:
    path: /mnt/usb/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1
