apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-db
        image: arm64v8/mongo
        resources:
          requests:
            cpu: 1
            memory: 500Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: andrew
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass
        livenessProbe:
          tcpSocket:
            port: 27017
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongodb-data 
            mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-data-claim
