apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels: 
    volume: mongo-vol
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3Gi
  nfs:
    server: 10.0.0.1
    path: /clust/share/mongo
