- name: Create cluster
  become: yes
  shell: |
    kubeadm init --pod-network-cidr 10.244.0.0/16 \
    --apiserver-advertise-address 10.0.0.1 \
    --apiserver-cert-extra-sans kubernetes.cluster.home

# TODO add config
# mkdir -p $HOME/.kube                                                                                             │
# sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config                                                         │
# sudo chown $(id -u):$(id -g) $HOME/.kube/config