- name: Create dhcp configuration 
  become: yes
  copy:
    src: ./files/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    backup: yes

- name: Install dhcp
  become: yes
  apt:
    pkg: isc-dhcp-server

- name: Set eth0 as default for isc service
  become: yes
  copy: 
    src: ./files/isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    backup: yes

- name: Restart isc service
  become: yes
  systemd:
    state: restarted
    name: isc-dhcp-server
